spring.application.name=knowledge-gap-platform
spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_gap_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=hv2gX9Eze5eA4H0iaLJuhof9rKsva6XcG2VcHLkKthduShu/UKSoDyKvg5x4kKgtzfOQDRb48YQGt7QsztYdzw==
jwt.expiration=7776000000