spring.application.name=knowledge-gap-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/okgip_platform
spring.datasource.username=postgres
spring.datasource.password=yaswanth123
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=knowledgegapintelligence@gmail.com
spring.mail.password=uhhcmmusivhmvauw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=daq7fsjnh
cloudinary.api-key=383211911689244
cloudinary.api-secret=3dTS_lsgHIl81vBdaqXRiFQ_whY

jwt.secret=hv2gX9Eze5eA4H0iaLJuhof9rKsva6XcG2VcHLkKthduShu
jwt.expiration=7776000000

spring.security.user.name=admin
spring.security.user.password=admin123

spring.data.redis.host=localhost
spring.data.redis.port=6379



spring.security.oauth2.client.registration.google.client-id=1026706091438-41ko5m8qqi4m1klal1vsgpt2o044thjh.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
