spring.application.name=knowledge-gap-platform

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.orm.jdbc.bind=OFF
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=knowledgegapintelligence@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cloudinary.cloud-name=daq7fsjnh
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

jwt.secret=${JWT_SECRET}
jwt.expiration=7776000000

spring.security.user.name=admin
spring.security.user.password=admin123

logging.level.org.springframework.security=DEBUG

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true


spring.security.oauth2.client.registration.google.client-id=1026706091438-41ko5m8qqi4m1klal1vsgpt2o044thjh.apps.googleusercontent.com

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,email,profile

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.model=gemini-flash-latest
