import React, { useEffect, useState } from "react";
import { BookOpen, Calendar, Loader2, MapPinned } from "lucide-react";
import {
    getCurrentLearningPath,
    getLearningPathCourses
} from "../../services/learningPathService";

const LearningPath = () => {
  const [learningPath, setLearningPath] = useState(null);
  const [courses, setCourses] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");



useEffect(() => {
  loadLearningPath();
}, []);

  const loadLearningPath = async () => {
    try {
      setLoading(true);

     const pathRes = await getCurrentLearningPath();

      setLearningPath(pathRes);

      const courseRes = await getLearningPathCourses(pathRes.id);

      const sortedCourses = [...courseRes].sort(
        (a, b) => a.sequenceOrder - b.sequenceOrder
      );

      setCourses(sortedCourses);
    } catch (err) {
      console.error(err);
      setError("Unable to load learning path.");
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-96">
        <Loader2 className="w-10 h-10 animate-spin text-blue-600" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-red-100 text-red-700 p-4 rounded-lg">
        {error}
      </div>
    );
  }

  if (!learningPath) {
    return (
      <div className="bg-white rounded-xl shadow p-10 text-center">
        <BookOpen className="mx-auto w-16 h-16 text-gray-400" />
        <h2 className="text-2xl font-semibold mt-4">
          No Learning Path Available
        </h2>
        <p className="text-gray-500 mt-2">
          AI has not generated a learning path yet.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-8">

      {/* Header */}

      <div className="bg-white rounded-xl shadow p-6">

        <div className="flex justify-between items-center flex-wrap gap-4">

          <div>

            <h1 className="text-3xl font-bold text-gray-800">
              Learning Path
            </h1>

            <p className="text-gray-500 mt-1">
              Personalized roadmap to improve your skills.
            </p>

          </div>

          <MapPinned className="text-blue-600 w-10 h-10" />

        </div>

      </div>

      {/* Details */}

      <div className="grid md:grid-cols-3 gap-5">

        <div className="bg-white rounded-xl shadow p-5">

          <p className="text-gray-500 text-sm">
            Generated By
          </p>

          <h2 className="font-semibold text-lg mt-2">
            {learningPath.generatedBy}
          </h2>

        </div>

        <div className="bg-white rounded-xl shadow p-5">

          <p className="text-gray-500 text-sm">
            Status
          </p>

          <span className="inline-block mt-2 px-3 py-1 rounded-full bg-green-100 text-green-700 font-medium">
            {learningPath.status}
          </span>

        </div>

        <div className="bg-white rounded-xl shadow p-5">

          <p className="text-gray-500 text-sm">
            Created
          </p>

          <h2 className="font-semibold mt-2">
            {new Date(learningPath.createdAt).toLocaleDateString()}
          </h2>

        </div>

      </div>

      {/* Timeline */}

      <div className="bg-white rounded-xl shadow p-6">

        <h2 className="text-2xl font-bold mb-8">
          Learning Roadmap
        </h2>

        <div className="relative">

          {courses.length === 0 ? (
            <div className="text-center py-10 text-gray-500">
              No courses available.
            </div>
          ) : (
            courses.map((course, index) => (

              <div
                key={course.id}
                className="relative flex gap-6 pb-10"
              >

                {/* Timeline */}

                <div className="flex flex-col items-center">

                  <div className="w-10 h-10 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold">

                    {course.sequenceOrder}

                  </div>

                  {index !== courses.length - 1 && (
                    <div className="w-1 flex-1 bg-blue-200 mt-2"></div>
                  )}

                </div>

                {/* Card */}

                <div className="flex-1 border rounded-xl p-6 hover:shadow-lg transition">

                  <h3 className="text-xl font-semibold">
                    {course.courseTitle}
                  </h3>

                  <div className="flex items-center gap-2 mt-3 text-gray-600">

                    <Calendar className="w-4 h-4" />

                    Estimated Duration:
                    <span className="font-medium">
                      {course.estimatedDays} Days
                    </span>

                  </div>

                  <button
                    className="mt-6 px-5 py-2 rounded-lg bg-blue-600 hover:bg-blue-700 text-white transition"
                    disabled
                  >
                    Start Learning
                  </button>

                </div>

              </div>

            ))
          )}

        </div>

      </div>

    </div>
  );
};

export default LearningPath;